### ISSUE TITLE
Error when running docker

### ISSUE THREAD

**Issue by thomasaustin** [zenaton/examples-node#21]
There seems to be an issue when running docker. I'm assuming because there's no Parallel directory in the root?

Dockerfile: `COPY Parallel /app/Parallel`

`ERROR: Service 'app' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder033036089/Parallel: no such file or directory`

**Comment by antoinereyt** [comment]
Fixed by https://github.com/zenaton/examples-node/commit/dc56bd879b2dc244fb0783fffbfb56ff34836eab
